%% Workflow: HITS v3 bitfield search against same-run STR timings
% Uses R5124_00368. Run the alignment audit first; the +8 event offset is
% currently the strongest simple-offset candidate in the sampled audit.

addpath('RHIT_imports');

dataDir = ['/Users/peterfelfer/Dropbox/01_research/0101_shared/' ...
           '010113_data-pool/APT_data/R5124_00368'];

hitsFile = fullfile(dataDir, 'R5124_00368.HITS');
strFile = fullfile(dataDir, 'R5124_00368.STR');

results = hitsSearchStrBitfields(hitsFile, strFile, ...
    'eventOffset', 8, ...
    'sampleStride', 1000, ...
    'maxRows', 50000, ...
    'minBits', 4, ...
    'maxBits', 24, ...
    'singleOnly', true);
