%% Workflow: HITS v3 residual search against same-run STR previous-ion deltas
% Uses R5124_00368. This tests whether the 8-byte HITS payload behaves like
% a predictive/residual code by correlating HITS byte/word predictors with
% STR_value(i) - STR_value(i-1).

addpath('RHIT_imports');

dataDir = ['/Users/peterfelfer/Dropbox/01_research/0101_shared/' ...
           '010113_data-pool/APT_data/R5124_00368'];

hitsFile = fullfile(dataDir, 'R5124_00368.HITS');
strFile = fullfile(dataDir, 'R5124_00368.STR');

resultsSingle = hitsSearchStrDeltas(hitsFile, strFile, ...
    'parentType', 'SINGLE', ...
    'eventOffset', 0, ...
    'sampleStride', 500, ...
    'maxRows', 50000);

resultsStatus = hitsSearchStrDeltas(hitsFile, strFile, ...
    'parentType', 'STATUS', ...
    'eventOffset', 0, ...
    'sampleStride', 20, ...
    'maxRows', 50000);

save('hits_str_delta_search_R5124.mat', 'resultsSingle', 'resultsStatus');
