function categories = functionCategories()
% FUNCTIONCATEGORIES Central list of API categories for documentation.
%
% categories = functionCategories()
%
% (c) by Prof. Peter Felfer Group @FAU Erlangen-Nurnberg

categories = struct();

categories.io = struct(...
    'name', 'Data Import/Export', ...
    'functions', {{'posLoad', 'posExport', 'posTableAddToHDF5', 'posTableFromHDF5', ...
                   'rangesExtractFromFile', 'hdf5FileCreateFromMetaDataList', ...
                   'patchToObj', 'patchToPly', 'posToObj'}});

categories.ions = struct(...
    'name', 'Ion and Range Management', ...
    'functions', {{'ionAdd', 'ionConvertName', 'ionConvertMode', 'ionsCreateIsotopeList', ...
                   'ionsCreateComplex', 'ionsMergePeaks', 'rangeAdd', ...
                   'rangeAddAll', 'rangeExtendToNeighbor', 'rangesFromPos', ...
                   'symbolConvertAtomicNumber'}});

categories.massspec = struct(...
    'name', 'Mass Spectrum Analysis', ...
    'functions', {{'massSpecPlot', 'massSpecAnalysis', 'massSpecComparison', ...
                   'massSpectrumLegend', 'backgroundEstimate', 'tofSpecBackgroundDetermination', ...
                   'peakBGCorrectedCount', 'chargeStateRatioCalculate'}});

categories.visualization = struct(...
    'name', 'Visualization', ...
    'functions', {{'scatterPlotPosData', 'scatterPlotPosWidget', 'colorSchemeCreate', ...
                   'colorSchemeIonAdd', 'valueToColor', 'movieCreateTurntableAnimation'}});

categories.roi = struct(...
    'name', 'Region of Interest', ...
    'functions', {{'roiCreateBox', 'roiCreateCylinder', 'roiCreateSphere', ...
                   'roiCreatePlane', 'roiFromObj', 'posInConvexHull'}});

categories.concentration = struct(...
    'name', 'Concentration Analysis', ...
    'functions', {{'posCalculateConcentrationSimple', 'posCalculateConcentrationBackgroundRemoved', ...
                   'posCalculateConcentrationDeconvolved', 'concentrationUncertainty', ...
                   'binApplyConcentrationKernel', 'calculate1Dprofile', 'calculate2Dprofile'}});

categories.proxigram = struct(...
    'name', 'Proxigram Analysis', ...
    'functions', {{'pointCreateProxigram', 'lineCreateProxigram', 'patchCreateProxigram', ...
                   'patchCreateInterfacialExcessMap', 'patchCreateExcessValue'}});

categories.cluster = struct(...
    'name', 'Cluster Analysis', ...
    'functions', {{'clusterDBSCAN', 'clusterDetermination', 'voronoiVolumeAnalysis', ...
                   'clusterIdentification', 'clusterSizeAnalyse'}});

categories.spatial = struct(...
    'name', 'Spatial Statistics', ...
    'functions', {{'spatialStatistics', 'spatialDistributionMap', 'dataQualityMetrics'}});

categories.crystallography = struct(...
    'name', 'Crystallography', ...
    'functions', {{'crystalOrientation', 'ipfColor', 'ipfHistogram', 'ipfMesh', ...
                   'misorientation', 'boundaryCharacter', 'stereoProj', 'plotOrientationCube'}});

categories.reconstruction = struct(...
    'name', 'Reconstruction', ...
    'functions', {{'posReconstruct3DGeiser', 'posReflectronCorrection', 'reflectronImageTransform'}});

categories.utilities = struct(...
    'name', 'Utilities', ...
    'functions', {{'setupToolbox', 'checkDependencies', 'APTConfig', 'batchProcess', ...
                   'ProgressTracker', 'validateInputs', 'runTests', 'sortIonCategories'}});

end
